// Generated by Haxe 3.3.0
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("Hello World of Haxe JS !!");
};
Main.main();
})();

//# sourceMappingURL=main.js.map